### ISSUE TITLE
HA blueprint not listening to frigate/events/summary

### ISSUE THREAD

**Issue by ttopholm** [mhaowork/amblegpt#8]
Hi, 

It seems the ha blueprint isn't subscribing to the frigate/events/summary topic, and therefore not getting the updated notifications.

**Comment by mhaowork** [comment]
Hi! Did you follow this part in the doc to (re-)import the blueprint? https://github.com/mhaowork/amblegpt#frigate-notifications-via-home-assistant-blueprint

If so, can you share your HomeAssistant logs like this? 
![image](https://github.com/mhaowork/amblegpt/assets/8702853/91fb165a-0224-4490-a09d-89d6bd61db01)

**Comment by ttopholm** [comment]
Yes, I followed the guide and copied the file. But I can't find anything in it related to frigate/events/summary topic. not even the one you link to.

**Comment by ttopholm** [comment]
Frigate Notification DEBUG (in loop): Info: Last Zones: [], Current zones: [], sublabel: None, iOS sound: False, Android Sound: enabled, Triggers: New Snapshot: False, Presence Changed: False, stationary moved: False, entered zones changed: False, sublabel changed: False, Conditions: Loitering: 0 or Presence Entity not home: OFF - PASS, zone filter TEST: OFF - PASS, multi-zone filter: OFF - PASS, state filter TEST: OFF - PASS image: "/api/frigate/notifications/1702073038.372822-j6isye/thumbnail.jpg" triggered by automation demo frigate mqtt topic frigate/events

**Comment by ttopholm** [comment]
This is the diff between yours (left) and SgtBatten (Right)
https://editor.mergely.com/x3Vxa5VJ

There isn't any diffs ;-)

**Comment by mhaowork** [comment]
Yeah, I made a stupid mistake forgetting to point to the correct branch. Now, the default `main` branch should have my changes aka https://github.com/mhaowork/HA_blueprints/blob/main/Frigate%20Camera%20Notifications/Stable.yaml

**Comment by ttopholm** [comment]
that did the trick.
